### ISSUE TITLE
获取记录闪退

### ISSUE THREAD

**Issue by XiaoMing-C137** [Makstein/SnowbreakGachaExport#5]
2.0.0-alpha版 已经准备好环境一获取记录就闪退。下面是报错：
[07:05:58:773 ERR] ApplicationDispatcherUnhandledException
System.Exception: Length of region array incorrect
   at SnowbreakToolbox.Services.PaddleOrcService.GetRegions(Mat image) in E:\C#\SnowbreakToolbox\SnowbreakToolbox\Services\PaddleOrcService.cs:line 89
   at SnowbreakToolbox.ViewModels.Pages.GachaHistoryViewModel.OnGetHistory() in E:\C#\SnowbreakToolbox\SnowbreakToolbox\ViewModels\Pages\GachaHistoryViewModel.cs:line 114
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Makstein** [comment]
游戏是不是没有全屏？

**Comment by XiaoMing-C137** [comment]
> 游戏是不是没有全屏？

全屏了 2560x1440 1920x1080无边框全屏和窗口化都试过

**Comment by Makstein** [comment]
游戏内有没有打开历史记录页面，这个我新版本readme忘写了

**Comment by XiaoMing-C137** [comment]
> 游戏内有没有打开历史记录页面，这个我新版本readme忘写了

感谢大佬 解决了 我看1.10不开历史记录也能有就以为不用开😂
